# Generated by Django 2.2 on 2021-10-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211019_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Design', 'Design'), ('Health', 'Health'), ('Music', 'Music'), ('Sport', 'Sport'), ('Travel', 'Travel'), ('Technology', 'Technology')], max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
